In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

2.6.0+cu124


**Introduction to Tensor**

In [3]:
#scaler
vector = torch.tensor(7)
vector

tensor(7)

In [4]:
vector.ndim

0

In [5]:
vector.shape

torch.Size([])

In [6]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

**Random Tensors**


In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1248, 0.3135, 0.8248, 0.8769],
        [0.3174, 0.0872, 0.8797, 0.4584],
        [0.5363, 0.1275, 0.3453, 0.8639]])

In [15]:
random_tensor.ndim

2

In [16]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

**Zeros and Ones**

In [17]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(size=(4, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**Creating a range of tensors and tensors-like**

In [19]:
ones_to_ten = torch.arange(start=0, end=11, step=1)
ones_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
zeros_like = torch.zeros_like(input=ones_to_ten)
zeros_like


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor datatypes**
**Note**: Tensor datatypes is one of the 3 big errors you will run into with Pytorch and Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [21]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [25]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [26]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

**Getting Information on the Tensors**

In [28]:
#To change the tensor type and device, run this and do not run the following code with random values
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False)
float_16_tensor

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [ ]:
float_16_tensor = torch.rand(2, 3, dtype=torch.float16)
float_16_tensor

In [ ]:
float_16_tensor.size, float_16_tensor.shape

In [ ]:
float_16_tensor.size()

In [29]:
print(float_16_tensor)
print(f"Datatype of tensor: {float_16_tensor.dtype}")
print(f"Shape of tensor: {float_16_tensor.shape}")
print(f"Device tensor is on: {float_16_tensor.device}")

tensor([3., 6., 9.], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3])
Device tensor is on: cpu


**Manipulating Tensors**

In [30]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
#Try out in-built functions of Pytorch
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [33]:
torch.add(tensor, 10)

tensor([11, 12, 13])

There are two main ways of doing matrix mltiplication:
1. Element-Wise Multiplication
2. Matrix multiplication (dot product)

In [34]:
#Element wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [36]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 1.07 ms, sys: 11 µs, total: 1.08 ms
Wall time: 1.39 ms


In [37]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 60 µs, sys: 10 µs, total: 70 µs
Wall time: 74.4 µs


tensor(14)

**One of the most errors in deep learning: Shape errors**

In [39]:
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [42]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

**To fix the error, we will do a transpose of the matrix**

In [43]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [44]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


**Finding the min, max, mean, sum, etc (tensor aggregation)**

In [45]:
#Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
#finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [47]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [48]:
# Find the mean  - note: the torch.mean() requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

**Find the positional min and max**

In [50]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
#find the position in the tensor that has the minimum value with argmin, returns index position of target tensor where the minimum value occurs.
x.argmin()

tensor(0)

In [52]:
#Find the position of the max value
x.argmax()

tensor(9)

**Reshaping, stacking, squeezing and unsqueezing tensors**
1. Reshaping: Reshapes an input tensor to a defined shape
2. View: Return a view of an input tensor of certain shape but keep the same memory as the original sensor
3. stacking: Combine multiple temsors on top of eachother
4. Squeeze: It removes all "1" dimensions from a tensor
5. Unsqueeze: Add a 1 dimension to a target tensor
6. Permute: Return a view of the input with dimensions permuted(swapped) in a certain way.



In [53]:
#Let's create a tensor
import torch
x= torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
#Change the future of Views.
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
#Changing z changes x
z[:, 0 ] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [57]:
#stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
#torch.squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [59]:
#torch.unsqueeze(): add a single dimension to a target tensor at a specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [60]:
#torch.permute: Rearange dimensions
x_original = torch.rand(size=(224, 224, 3)) #height, width and colour_channels

#permute the original tensor to rearange the axis (or dim) order

x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #Colour channel, heights and width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [63]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

**indexing (Selecting data from tensors)**

In [64]:
import torch
x= torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [65]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [66]:
x[0][0]

tensor([1, 2, 3])

In [75]:
#Let us index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [79]:
#Index on x to return 3, 6, 9
print(x[:, :, 2])
print(x[0, 0, :])

tensor([[3, 6, 9]])
tensor([1, 2, 3])


**PyTorch tensors and Numpy**
Numpy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it
- Data in Numpy, want in PyTorch tensor torch.from_numpy(ndarray)
- PyTorch Tensor Numpy, torch.Tensor.numpy()

In [92]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  #When converting from numpy to pytorch, the datatype is the default one
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [88]:
array.dtype

dtype('float64')

In [93]:
#Change the value of the array, what will this do to tensor ?
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([1., 1., 1., 1., 1., 1., 1.]))

In [94]:
#Change the tensor, what happens to numpy_tensor ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**REPRODUCIBILITY (Trying to take random out of Random)**

In short, how a Neural Network learns:

Start with random numbers - Tensor operations - Update random numbers to try and make them of the data - again - again

To reduce the randomness in Neural Networks and Pytorch comes the concept of a **random seed**. Essentially what random seed does is "flavour " the randomness.

In [96]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3056, 0.4904, 0.6145, 0.5321],
        [0.2048, 0.3105, 0.2919, 0.0205],
        [0.3421, 0.5033, 0.5892, 0.0759]])
tensor([[1.7798e-04, 8.1900e-01, 3.6817e-02, 9.4830e-01],
        [7.0338e-02, 9.1584e-01, 6.1347e-01, 8.3169e-01],
        [5.8161e-01, 5.9857e-01, 2.3176e-01, 9.3225e-01]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [99]:
#Let us make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Running Tensors and Pytorch objects on the GPUs (And making faster computation)**
GPUs = faster computation on numbers, thanks to CUDA+NVIDIA hardware + Pytorch working behind the scenes dory (good)

In [1]:
# Getting a GPU
!nvidia-smi

Thu May  1 23:23:19 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   61C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
#Check for the GPU access with PyTorch

import torch
torch.cuda.is_available()

True

**Since PyTorch can run on CPU and GPU, it is best practice to use Setup agnostic**

In [3]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#Count number of devices
torch.cuda.device_count()

1

**Putting tensors and Models on the GPU**

In [5]:
#create a tensor (default on the CPU)

tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

**Moving Tensors back to the CPU**

In [6]:
#If the tensor is on GPU, It cannot transform it to CPU
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [7]:
#To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [8]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')